apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: true
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: loki
      tracesToMetrics:
        datasourceUid: prometheus
        tags:
          - key: service.name
            value: service
          - key: job
        queries:
          - name: Sample query
            query: 'sum(rate(tempo_request_duration_seconds_bucket[5m]))'
      tracesToLogs:
        datasourceUid: loki
        tags:
          - service.name
          - job
        mappedTags:
          - name: service.name
            value: service
        mapTagNamesEnabled: false
        spanStartTimeShift: 1h
        spanEndTimeShift: 1h
        filterByTraceID: false
        filterBySpanID: false
    version: 1