basic_auth_users:
  admin: $apr1$GamF4o6N$Zr5ybc4fZ14VpE5iD0QSd0

# TLS disabled for now - enable after generating certificates
# tls_server_config:
#   cert_file: /etc/ssl/certs/prometheus.crt
#   key_file: /etc/ssl/private/prometheus.key