basic_auth_users:
  admin: $2y$05$.xy0pfy2Ljhh2xho2nhs/e378sfQG830MKxcwQsVG2F/B.P5/tJWm

# TLS disabled for now - enable after generating certificates
# tls_server_config:
#   cert_file: /etc/ssl/certs/prometheus.crt
#   key_file: /etc/ssl/private/prometheus.key