basic_auth_users:
  admin: $2y$05$IOVh7COC/0a0xrwSkz/qNuzUR4EGwLSCN68rpPZgJscRJnNQh9Nm2

# TLS disabled for now - enable after generating certificates
# tls_server_config:
#   cert_file: /etc/ssl/certs/prometheus.crt
#   key_file: /etc/ssl/private/prometheus.key