# Production environment - uses base docker-compose.yml
# This file exists for potential production-specific overrides
version: '3.8'

services:
  grafana:
    environment:
      - GF_SECURITY_ADMIN_PASSWORD_FILE=/run/secrets/grafana_admin_password
